name: Auto Commit Changes
on:
  push:
    branches:
      - main
jobs:
  auto-commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Make Changes
        run: |
          # Your commands to modify files go here
          echo "New content" >> file.txt
      - name: Commit Changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated commit"
